require 'rubygems'
require 'bundler/setup'

require 'pry-byebug' # binding.pry to debug!

# Coverage
ENV['CODECLIMATE_REPO_TOKEN'] = '18ddab0ec2f7be2430569f2ffc7dee169da139b792172d3992a6aacba1f50877'
require 'codeclimate-test-reporter'
CodeClimate::TestReporter.start

# This Gem
require 'spiced_gracken'

SimpleCov.start do
  add_filter "/lib/spiced_gracken/display/bash/"
  add_filter "/lib/spiced_gracken/display/null/"
  add_filter "/lib/spiced_gracken/display/terminal_curses/"
end

Dir[File.dirname(__FILE__) + '/support/**/*.rb'].each { |file| require file }

# This file was generated by the `rspec --init` command. Conventionally, all
# specs live under a `spec` directory, which RSpec adds to the `$LOAD_PATH`.
# Require this file using `require "spec_helper"` to ensure that it is only
# loaded once.
#
# See http://rubydoc.info/gems/rspec-core/RSpec/Core/Configuration
RSpec::Expectations.configuration.warn_about_potential_false_positives = false
RSpec.configure do |config|
  config.run_all_when_everything_filtered = true
  config.filter_run :focus
  # Run specs in random order to surface order dependencies. If you find an
  # order dependency and want to debug it, you can fix the order by providing
  # the seed, which is printed after each run.
  #     --seed 1234
  config.order = 'random'

  config.before(:each) do
    setup_database
  end
end
